apiVersion: v1
kind: ConfigMap
metadata:
  name: eif-cfg
data:
  CAPE_EIF_PATH: s3://gabs-aws-enclave-image-files/{{.Values.eifFile}}

---
apiVersion: v1
kind: Pod
metadata:
  name: download-eif-pod
spec:
  containers:
  - name: download-eif
    image: amazon/aws-cli
    env:
    - name: CAPE_EIF_PATH
      valueFrom:
        configMapKeyRef:
          name: eif-cfg
          key: CAPE_EIF_PATH
    command: ["aws", "s3", "ls" "$(CAPE_EIF_PATH)"]